### ISSUE TITLE
Database not installing

### ISSUE THREAD

**Issue by trisketz** [qubeshub/com_partners#27]
Attempted to install this component off a fresh hubzero-vagrant installation. The image below is what I got when I installed the component in admin.
<img width="1667" alt="screen shot 2017-07-20 at 12 45 19 pm" src="https://user-images.githubusercontent.com/21963909/28433509-8db651c2-6d51-11e7-8f8d-d4761a14df1c.png">
Here is what I get when I attempt to go to the partners page on the front end. 
<img width="1461" alt="screen shot 2017-07-20 at 12 48 12 pm" src="https://user-images.githubusercontent.com/21963909/28433561-bded8a5e-6d51-11e7-9e12-5c7a0c6ace7a.png">
Not sure what I'm missing or if I need to enable something on the back end.

Also, as an fyi, your installation instructions are for the Dr Who component. Not sure if you intended that.

Jenny

**Comment by jrharless** [comment]
updated the README. You are going to need to ssh into your virtual box, navigate to com_partners and run the script`mysql -u root -p example < install.sql`
or  from the hubzero-vagrant root directory run:
`php muse migration -f`

**Comment by trisketz** [comment]
I got the script to work and the Partners page will now display on the front end. I thought Partners would be listed as a component (under the Components menu) in the administrator? It's not displaying for me.

**Comment by jrharless** [comment]
if you ran it with the migration script, itll be at the bottom of the list
of components. not sure how to make it be alphabetical :( but ill look into
it

On Jul 21, 2017 2:14 PM, "trisketz" <notifications@github.com> wrote:

I got the script to work and the Partners page will now display on the
front end. I thought Partners would be listed as a component (under the
Components menu) in the administrator? It's not displaying for me.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/qubeshub/com_partners/issues/27#issuecomment-317074329>,
or mute the thread

**Comment by jrharless** [comment]
Ok I have it working on mine by changing the migration script to uppercase Partners. It may or may not work on yours as I have had some bugs in the past. Let me know.

**Comment by trisketz** [comment]
It worked! Thank you much :)
